-- install UF_ACTIVE_INSTALLMENT from sql
ALTER TABLE `oxarticles` ADD `UF_ACTIVE_INSTALLMENT` TINYINT(1) DEFAULT 0 COMMENT "Active installment";
-- remove UF_ACTIVE_INSTALLMENT from sql
ALTER TABLE `oxarticles` DROP COLUMN `UF_ACTIVE_INSTALLMENT`;

-- install UF_INSTALLMENT_NUMBER_OF_MONTHS from sql
ALTER TABLE `oxarticles` ADD `UF_INSTALLMENT_NUMBER_OF_MONTHS` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "Number of installment months";
-- remove UF_INSTALLMENT_NUMBER_OF_MONTHS from sql
ALTER TABLE `oxarticles` DROP COLUMN `UF_INSTALLMENT_NUMBER_OF_MONTHS`;

-- install UF_INSTALLMENT_NUMBER_OF_MONTHS from sql
ALTER TABLE `oxarticles` ADD `UF_INSTALLMENT_PREPAYMENT` DOUBLE UNSIGNED NOT NULL DEFAULT 0 COMMENT "Article prepayment";
-- remove UF_INSTALLMENT_PREPAYMENT from sql
ALTER TABLE `oxarticles` DROP COLUMN `UF_INSTALLMENT_PREPAYMENT`;